build_image: shippableimages/ubuntu1404_nodejs
commit_container: smvanveen/shippable-test
cache: true

before_script:
    - sudo apt-get update
    - sudo apt-get install -y ruby nginx
    - gem install sass
    - npm install
    - node node_modules/.bin/bower install --allow-root

script:
    - node node_modules/.bin/grunt default
