build_image: shippableimages/ubuntu1404_nodejs
commit_container: smvanveen/shippable-test
cache: true
language: node_js

before_script:
    - sudo apt-get update
    - sudo apt-get install -y ruby nginx phantomjs
    - gem install sass
    - npm install
    - node node_modules/.bin/bower install --allow-root
    - mkdir -p shippable/testresults/
    - mkdir -p shippable/codecoverage/

script:
    - node node_modules/.bin/grunt default
    - node node_modules/.bin/grunt karmaconfig:unit karma:continuous
