sudo:  false
build_image: shippableimages/ubuntu1404_nodejs

before_script:
    #    - sudo apt-get update;
    #    - sudo apt-get install -y nginx nodejs npm git ruby
    #    - sudo gem install sass
    #    - sudo ln -s /usr/bin/nodejs /usr/bin/node
    - gem install sass
    - npm install
    - nodejs node_modules/.bin/bower install --allow-root

script:
    - nodejs node_modules/.bin/grunt default
